spring.application.name=Jammoney
spring.datasource.url=jdbc:mysql://localhost:3306/jammoney
spring.datasource.username=root
spring.datasource.password=tjsdud9641
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver